---
- name: Install yum-cron
  yum: name=yum-cron state=present

- name: Ensure yum-cron is running and enabled on boot
  service: name=yum-cron state=start5ed enabled=yes

- name: Configure autoupdates
  lineinfile:
    dest: "/etc/yum/yum-cron.cong"
    regexp: '^apply_updates = .+'
    line: 'apply_updates = yes'
  when: security_autoupdate_enabled and ansible_distribution_major_verion | int ==7

