---
- name: Update SSH configuration to be more secure
  lineinfile:
    dest: "{{ security_ssh_config_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
   with_items:
     - regexp: "^PasswordAuthentication"

- name: Add configured user accounts to passwordless sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item }}'
    line: '{{ item }} ALL=(ALL) ALL'
    state: present
    validate: 'visudo -cf %s'
  with_items: "{{security_sudoers_passworded }}"
  when: security_sudoers_passworded | length > 0

