---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Ubuntu.yml
  when: ansible_os_family == 'Ubuntu'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debain'

- include: setup-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'

##Host info  
- include: vhosts.yml

- name: Copy nginx configuration in place
  template:
    src: nginx.xonf.j2
    dest: "{{ nginx_conf_file_path }}" 
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: Ensure nginx is started and enabled at boot
  service: name=nginx state=started enabled=yes

